name: Build Win32/x64 with all deps (Release)

on: [push, workflow_dispatch]

jobs:
  call-workflow-build-win32:
    uses: ./.github/workflows/workflow-rebuild-all-deps.yml
    with:
      platform-arch: Win32
      build-config: Release

  call-workflow-build-x64:
    uses: ./.github/workflows/workflow-rebuild-all-deps.yml
    with:
      platform-arch: x64
      build-config: Release
