name: Build and Upload Artifacts
# TODO later test and lint
# TODO test building library dependencies (the prebuilt stuff)



# GH Action Reusable Workflow -- https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:
    inputs:
      platform-arch:
        required: true
        type: string
      build-config:
        required: true
        type: string



# WTL is a submodule, so this GH actions specifically clones ONLY that
# This will match the formal release build environment.
#
# While I would like to do a submodule clone with checkout@v3, there's no option
# to check out only ONE submodule.  There's a lot of submodules in this project
# which are not directly required for building, and that seems fairly inefficient.



jobs:
  build:
    # if windows-latest, might not find VS 2019
    runs-on: windows-2019


    steps:
    - uses: actions/checkout@v3

    - name: setup-msbuild
      # https://github.com/marketplace/actions/setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        # Fixed on Visual Studio 2019 -- https://docs.microsoft.com/en-us/visualstudio/releases/2019/history
        vs-version: '[16.0,17.0)'
        msbuild-architecture: ${{ inputs.platform-arch }}

    # https://gist.github.com/hibearpanda/d5b5b58bd319132ffd7af606ffa333fc
    #  https://github.com/felixrieseberg/electron-wix-msi/issues/1#issuecomment-674598795
    #  https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
    #  https://stackoverflow.com/a/64831469
    #  https://github.community/t/set-path-for-wix-toolset-in-windows-runner/154708
    - name: Set path for candle and light
      env:
        WIX_PATH: ${{ env.wix }}
      run: |
        #echo "$env:WIX_PATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        # https://github.community/t/set-path-for-wix-toolset-in-windows-runner/154708/3
        $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
        echo "$PATH"
        # check that they're found
        where.exe candle.exe
        where.exe light.exe

    - name: WTL Submodule init
      # Run git commands directly without using the GH checkout action
      run: git submodule update --init deps/WTL-sf

    - name: Build Solution
      run: msbuild.exe /property:Platform=${{ inputs.platform-arch }} /property:configuration="${{ inputs.build-config }}" src\JPEGView.sln

      shell: cmd
    - name: Upload Outputs
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ inputs.platform-arch }}
        path: |
          src/JPEGView/bin
          src/JPEGView.Setup/bin
